#!/usr/bin/env bash
# Installs nginx with the below configuration
#+    Listens on port 80
#+    Returns a page containing 'Hello World' when queried
#+    at the root with curl GET request.
#+    Configures/redirect_me as a "301 Moved Permanently"
#+    Includes a custom 404 page contaning:
#+    "Ceci n'est pas une page"
#+    contains a custom HTTP response header named X-Served-By.
#+    The value of X-Served-By is the hostanme of the server.

sudo apt update
sudo apt install -y nginx

sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.html

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo chown ubuntu:ubuntu /etc/nginx/sites-available/default
sudo chmod 700 /etc/nginx/sites-available/default
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;
    server_name _;
    location /redirect_me {
        return 301 http://google.com/;
    }
    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" >  /etc/nginx/sites-available/default

sudo service nginx restart
~                                            
