#!/usr/bin/env bash
# bash script to automate the fix on a buggy ubuntu nginx server installation                                                                                                                                     
                                                                                                                       
# Go to sites-enabled folder for Nginx                                                                                                                    
cd /etc/nginx/sites-enabled/ || exit;                                                                                                                             
# Delete the default file                                                                                                                               
rm default;

# Create a symbolic link to the deafult file in sites-available                                                                                             
ln -s /etc/nginx/sites-available/default default; 

# Restart Nginx                                                                                                                                           
service nginx restart 
