#!/usr/bin/env bash
#Sets nginx for listening to 80 port (A minimum code version of task 0)
sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
