#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely with
#+ a sleep 2 in between each iteration.
#   Displays "I am invincible!!!" in between each iteration.

trap 'echo "I am invincible!!!"' SIGTERM
counter=2
while [ $counter -gt 0 ]; do
    echo "To infinity and beyond"
    sleep 2
done
