#!/usr/bin/env bash
# run command as another user while taking a single argument

if [ $# -gt 1 ]
then 
  echo "this program accepts only one argument!"
elif [ $# -lt 1 ]
then
  echo "supply the user argument"
else
  sudo -u "$1" whoami
fi
