#!/usr/bin/env bash
# Run Nginx as the nginx user without root privileges.

# configure nginx to listen on ports 8080
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# sets permissions so that, (U)ser / owner can read, can write and can't execute. 
# (G)roup can read, can't write and can't execute. 
# (O)thers can read, can't write and can't execute.
chmod 644 /etc/nginx/nginx.conf

# stop the apache service
pkill apache2
# start the nginx service as user: nginx
sudo -u nginx service nginx start
